# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mesh_beacon.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import channel_pb2 as meshtastic_dot_aiomeshtastic_dot_protobuf_dot_channel__pb2
from . import config_pb2 as meshtastic_dot_aiomeshtastic_dot_protobuf_dot_config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3meshtastic/aiomeshtastic/protobuf/mesh_beacon.proto\x12!meshtastic.aiomeshtastic.protobuf\x1a/meshtastic/aiomeshtastic/protobuf/channel.proto\x1a.meshtastic/aiomeshtastic/protobuf/config.proto\"\xe9\x02\n\nMeshBeacon\x12\x0f\n\x07message\x18\x01 \x01(\t\x12I\n\roffer_channel\x18\x02 \x01(\x0b\x32\x32.meshtastic.aiomeshtastic.protobuf.ChannelSettings\x12U\n\x0coffer_region\x18\x03 \x01(\x0e\x32?.meshtastic.aiomeshtastic.protobuf.Config.LoRaConfig.RegionCode\x12[\n\x0coffer_preset\x18\x04 \x01(\x0e\x32@.meshtastic.aiomeshtastic.protobuf.Config.LoRaConfig.ModemPresetH\x00\x88\x01\x01\x12!\n\x14offer_frequency_slot\x18\x05 \x01(\rH\x01\x88\x01\x01\x42\x0f\n\r_offer_presetB\x17\n\x15_offer_frequency_slotBf\n\x14org.meshtastic.protoB\x10MeshBeaconProtosZ\"github.com/meshtastic/go/generated\xaa\x02\x14Meshtastic.Protobufs\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meshtastic.aiomeshtastic.protobuf.mesh_beacon_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024org.meshtastic.protoB\020MeshBeaconProtosZ\"github.com/meshtastic/go/generated\252\002\024Meshtastic.Protobufs\272\002\000'
  _globals['_MESHBEACON']._serialized_start=188
  _globals['_MESHBEACON']._serialized_end=549
# @@protoc_insertion_point(module_scope)
